export const Advisors = [
  {
    name: 'Lionel Khoury',
    photo: 'lionel.jpeg',
    position: '',
    linkedin: 'https://ca.linkedin.com/in/lionel-khoury-3b0314b',
    text: 'Echelon Consulting Group (ECGI)',
  },
  {
    name: 'Landon Miller',
    photo: 'landon.jpeg',
    position: '',
    linkedin: 'https://ca.linkedin.com/in/landon-miller-1067b7a5',
    text: 'Ohkwa:ri Health Group',
  },
  {
    name: 'Rob Strickland',
    photo: 'rob.png',
    position: '',
    linkedin: 'https://www.linkedin.com/in/robert-strickland-3414a5/',
    text: 'M37 Ventures',
  },
  {
    name: 'OG Arabian Prince',
    photo: 'OGArab.jpeg',
    position: '',
    linkedin: 'https://www.linkedin.com/in/ogarabianprincenwa/',
    text: 'MdDAO',
  },
  {
    name: 'Thierry Pepin',
    photo: 'thierry.png',
    position: '',
    linkedin: 'https://www.linkedin.com/in/tpepin/?originalSubdomain=ca',
    text: 'True Block Capital',
  },
  {
    name: 'Andrea Kalmans',
    photo: 'andrea.jpeg',
    position: '',
    linkedin: 'https://www.linkedin.com/in/akalmans/',
    text: 'Lontra Ventures',
  },
  {
    name: 'Salvador Gala',
    photo: 'salvador.jpeg',
    position: '',
    linkedin: 'https://www.linkedin.com/in/salvadorgala',
    text: 'Escape Velocity (EV3)',
  },
];
